name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      platform: linux-musl
      channel: stable
      target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - uses: XAMPPRocky/get-github-release@v1
        with:
          owner: rust-embedded
          repo: cross
          matches: ${{ env.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x /tmp/cross
      - run: ci/set_rust_version.bash $channel $target
      - run: ci/build.bash /tmp/cross $target
      - run: ci/test.bash /tmp/cross $target
