name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-cross:
    runs-on: ubuntu-latest
    env:
      platform: linux-musl
    steps:
      - uses: XAMPPRocky/get-github-release@v1
        id: cross
        with:
          owner: rust-embedded
          repo: cross
          matches: ${{ env.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: cross-${{ env.platform }}
          path: ${{ steps.cross.outputs.install_path }}

  linux:
    runs-on: ubuntu-latest
    needs: install-cross
    env:
      channel: stable
      target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - name: Download Cross
        uses: actions/download-artifact@v3
        with:
          name: cross-linux-musl
          path: /tmp/
      - run: chmod +x /tmp/cross
      - run: ci/set_rust_version.bash $channel $target
      - run: ci/build.bash /tmp/cross $target
      - run: ci/test.bash /tmp/cross $target
